audit_header: false
title: South Florida Video Blog with Danielle Damianov
description: Our mission at Guaranteed Rate is to be your best resource for Miami real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Guaranteed Rate, your professional Miami Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Danielle Damianov
  title:
  license_number:
  about_markdown: |
    I have 17 Years in the Mortgage and Real Estate Industry. I have spent 10 years in Mortgage Lending as a Mortgage Broker, Mortgage Processor and owner of a Mortgage Company/ Correspondent Lender. In 2009, I decided to go into Real Estate Full time and sold Residential Real Estate in Southwest Florida (Fort Myers/ Naples) and South Florida (Miami/ Ft. Lauderdale) for the past 7 years. Although I have had many successes in the Real Estate business, my passion has always been helping clients with their financing needs. I am dedicated to finding my clients the best loan programs and rates and offer a variety of loans to include Purchase, Jumbo Loans, Construction to Perm, Refinance, VA Loans, FHA Loans, and Renovation Loans. My 17 Years experience in both Real Estate and Mortgage will allow me to help my clients with their financing needs throughout Florida while offering the same commitment, dedication and the Top Notch customer service.
  brand: Guaranteed Rate
  brokerage:
  market: Miami
  address: '24301 Walden Center Drive #3106<br>Bonita Springs, FL 34134'
  phone: 786-359-7976
  phone_type:
  phone2:
  phone2_type:
  email: danielle.damianov@rate.com
  url: https://www.rate.com/loan-expert/danielledamianov

CTAs:
  first_CTA_text: Apply Now
  first_CTA_URL: https://app.guaranteedrate.com/#/start
  second_CTA_text: Today's Rates
  second_CTA_URL: https://www.guaranteedrate.com/mortgage-rates

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Find the Perfect Loan for You"
    CTA_text: "With just a few easy clicks!"
    CTA_link_text: "Apply Now"
    CTA_url: https://app.guaranteedrate.com/#/start

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Compare Low Mortgage Rates"
    CTA_text2: "Get personalized rates, available through Guaranteed Rate’s Online Division."
    CTA_link_text2: "Today's Rates"
    CTA_url2: https://www.guaranteedrate.com/mortgage-rates

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/guaranteedRate
  linkedin_url: https://www.linkedin.com/in/danielle-damianov-33b57a/
  youtube_url: https://www.youtube.com/channel/UCc4dTfT3Eh1lU59jjsp4EuQ
  twitter_url: https://twitter.com/GuaranteedRate
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Miami Real Estate Podcast with Danielle Damianov'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Miami Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Guaranteed Rate - your professional Miami Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Miami, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Danielle Damianov'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: South Florida Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#2C668B'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
